// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using earrings.Data;

#nullable disable

namespace earrings.Migrations
{
    [DbContext(typeof(EarringsDbContext))]
    [Migration("20240528204350_firstmigrationearrings")]
    partial class firstmigrationearrings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("earrings.Models.Earrings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Earrings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f5b3b3b3-3b3b-3b3b-3b3b-3b3b3b3b3b3b"),
                            Description = "Söta hängande avokadoörhängen",
                            Image = "/avokado.png",
                            Name = "Avokados",
                            Price = 50.0
                        },
                        new
                        {
                            Id = new Guid("f5b3b3b3-3b3b-3b3b-3b3b-3b3b3b3b3b3c"),
                            Description = "Spökörhängen. Perfekta till Halloween!",
                            Image = "/spoken.png",
                            Name = "Spöken",
                            Price = 50.0
                        },
                        new
                        {
                            Id = new Guid("f5b3b3b3-3b3b-3b3b-3b3b-3b3b3b3b3b3d"),
                            Description = "Tassar till husse eller matte!",
                            Image = "/tassar.png",
                            Name = "Hundtassar",
                            Price = 50.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
